name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Semgrep Analyze
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:2769f9ce8e44d2cd7d31e1d660e25b054ff3443fc5f5130fbc6d3a6e7dcec4c2 # 1.47.0
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # We've changed the behavior a little, instead of forcing a fail on `semgrep scan` step
      # we force the upload, and manage any results in the sencondary CodeQL Analysis of the
      # uploaded files. Configuration is handled in Settings --> Security --> CodeQL
      - name: Semgrep Scan
        run: |
          echo "SEMGREP_TO_UPLOAD=semgrep.sarif" >> $GITHUB_ENV
          semgrep scan --sarif --output=semgrep.sarif --exclude="frontend/src/uswds" --metrics=off
        env:
          SEMGREP_RULES: "p/default"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@17a820bf2e43b47be2c72b39cc905417bc1ab6d0 # v3
        with:
          sarif_file: ${{ env.SEMGREP_TO_UPLOAD }}
        if: always()
